# Generated by Django 6.0.6 on 2026-06-28 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['is_featured'], name='service_featured_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['category', 'display_order'], name='service_cat_order_idx'),
        ),
    ]
