# Generated by Django 6.0.6 on 2026-06-28 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0001_initial'),
        ('services', '0002_service_service_featured_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='inquiry',
            index=models.Index(fields=['status', '-created_at'], name='inquiry_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='inquiry',
            index=models.Index(fields=['-created_at'], name='inquiry_created_idx'),
        ),
        migrations.AddIndex(
            model_name='inquiry',
            index=models.Index(fields=['buyer_type', 'status'], name='inquiry_buyer_status_idx'),
        ),
    ]
