# Generated by Django 6.0.6 on 2026-06-28 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='company_registration',
            field=models.CharField(blank=True, max_length=10, verbose_name='Companies House Registration No.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='founded_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Founded Year'),
        ),
    ]
