# Generated by Django 6.0.6 on 2026-07-09 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesettings_company_registration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='company_registration',
            field=models.CharField(blank=True, help_text='Companies House registration number (e.g. 12345678)', max_length=10, verbose_name='Companies House Registration No.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='founded_year',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Year the company was founded — appears in structured data', null=True, verbose_name='Founded Year'),
        ),
    ]
