# Generated by Django 6.0.6 on 2026-07-10 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_sitesettings_company_registration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_meta_description',
            field=models.TextField(blank=True, help_text='SEO meta description for the About page.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_location_text',
            field=models.CharField(blank=True, help_text="Footer line, e.g. 'Serving clients across the Kingdom of Saudi Arabia.'", max_length=300),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='portfolio_meta_description',
            field=models.TextField(blank=True, help_text='SEO meta description for the Portfolio page.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='services_meta_description',
            field=models.TextField(blank=True, help_text='SEO meta description for the Services landing page.'),
        ),
    ]
