# Generated by Django 6.0.6 on 2026-07-10 00:29

from django.db import migrations

# The exact strings that previously lived hardcoded in the views/templates.
# Backfilled onto the singleton so the rendered site is byte-for-byte unchanged
# until the founder edits them in the admin.
FOOTER_LOCATION_TEXT = "Serving clients across the West Midlands and surrounding areas."
ABOUT_META = (
    "Learn about Pioneer Consultants — an independent construction consultancy "
    "delivering project, cost, and commercial expertise from concept to completion."
)
SERVICES_META = (
    "Pioneer Consultants offers specialist construction consultancy services — "
    "project management, cost consultancy, and commercial advisory for clients, "
    "contractors, and consultancies."
)
PORTFOLIO_META = (
    "Browse Pioneer Consultants' project portfolio — "
    "infrastructure and construction case studies across the West Midlands."
)

_BACKFILL = {
    "footer_location_text": FOOTER_LOCATION_TEXT,
    "about_meta_description": ABOUT_META,
    "services_meta_description": SERVICES_META,
    "portfolio_meta_description": PORTFOLIO_META,
}


def backfill(apps, schema_editor):
    SiteSettings = apps.get_model("core", "SiteSettings")
    obj, _ = SiteSettings.objects.get_or_create(pk=1)
    changed = False
    for field, value in _BACKFILL.items():
        if not getattr(obj, field):
            setattr(obj, field, value)
            changed = True
    if changed:
        obj.save()


def unbackfill(apps, schema_editor):
    SiteSettings = apps.get_model("core", "SiteSettings")
    obj = SiteSettings.objects.filter(pk=1).first()
    if obj is None:
        return
    for field, value in _BACKFILL.items():
        if getattr(obj, field) == value:
            setattr(obj, field, "")
    obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_sitesettings_about_meta_description_and_more"),
    ]

    operations = [
        migrations.RunPython(backfill, unbackfill),
    ]
