# Generated by Django 6.0.6 on 2026-07-10 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_default_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='brand_name',
            field=models.CharField(default='London Summit Consultancy', max_length=100),
        ),
    ]
