# Generated by Django 6.0.6 on 2026-07-13 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rebrand_site_copy'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='avatar',
            field=models.ImageField(blank=True, help_text="Optional client headshot. When empty, the client's initials are shown instead.", upload_to='testimonials/'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='headline',
            field=models.CharField(blank=True, help_text="Optional short, bold card title, e.g. 'Delivered ahead of programme'.", max_length=120),
        ),
    ]
