# Generated by Django 6.0.6 on 2026-07-10 01:08

import apps.tenders.storage
import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalTender',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('reference', models.CharField(db_index=True, editable=False, help_text='Auto-generated, e.g. PCL-2025-001.', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('client_name', models.CharField(max_length=150)),
                ('client_email', models.EmailField(blank=True, max_length=254)),
                ('sector', models.CharField(choices=[('infrastructure', 'Infrastructure'), ('construction', 'Construction')], max_length=30)),
                ('description', models.TextField()),
                ('deadline', models.DateField(blank=True, null=True)),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated contract value in GBP.', max_digits=12, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('won', 'Won'), ('lost', 'Lost'), ('withdrawn', 'Withdrawn')], default='draft', max_length=20)),
                ('status_changed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Tender',
                'verbose_name_plural': 'historical Tenders',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(editable=False, help_text='Auto-generated, e.g. PCL-2025-001.', max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('client_name', models.CharField(max_length=150)),
                ('client_email', models.EmailField(blank=True, max_length=254)),
                ('sector', models.CharField(choices=[('infrastructure', 'Infrastructure'), ('construction', 'Construction')], max_length=30)),
                ('description', models.TextField()),
                ('deadline', models.DateField(blank=True, null=True)),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated contract value in GBP.', max_digits=12, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('won', 'Won'), ('lost', 'Lost'), ('withdrawn', 'Withdrawn')], default='draft', max_length=20)),
                ('status_changed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_to', models.ManyToManyField(blank=True, related_name='assigned_tenders', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tenders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tender',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenderDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('revision', models.CharField(help_text="Free-form revision label, e.g. 'Rev A', 'Rev 1'.", max_length=10)),
                ('file', models.FileField(blank=True, max_length=500, storage=apps.tenders.storage.tender_document_storage, upload_to=apps.tenders.storage.tender_document_upload_to)),
                ('file_size_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('is_superseded', models.BooleanField(default=False)),
                ('processing_status', models.CharField(choices=[('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='tenders.tender')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tender Document',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='tender',
            index=models.Index(fields=['status'], name='tender_status_idx'),
        ),
        migrations.AddIndex(
            model_name='tender',
            index=models.Index(fields=['deadline'], name='tender_deadline_idx'),
        ),
        migrations.AddIndex(
            model_name='tender',
            index=models.Index(fields=['created_at'], name='tender_created_idx'),
        ),
        migrations.AddIndex(
            model_name='tenderdocument',
            index=models.Index(fields=['tender', 'is_superseded'], name='tenderdoc_tender_super_idx'),
        ),
        migrations.AddConstraint(
            model_name='tenderdocument',
            constraint=models.UniqueConstraint(fields=('tender', 'title', 'revision'), name='uniq_tender_document_title_revision'),
        ),
    ]
