# Generated by Django 6.0.6 on 2026-07-10 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderdocument',
            name='ai_summary',
            field=models.TextField(blank=True, help_text='Gemini-generated summary of the document.'),
        ),
    ]
