# Generated by Django 6.0.6 on 2026-07-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0003_tendermessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenderdocument',
            name='ai_summary',
            field=models.TextField(blank=True, help_text='AI-generated summary of the document.'),
        ),
    ]
