# Generated by Django 6.0.6 on 2026-07-10 11:36
#
# Swaps the standalone status index for a (status, -created_at) composite that
# serves the list's filter+sort in one scan. Tenders is a new, small table, so a
# plain index build is fine. NOTE for the future: if this table grows large and
# live, add/drop indexes with AddIndexConcurrently / RemoveIndexConcurrently
# (django.contrib.postgres.operations, atomic = False) to avoid a write lock.
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenders", "0004_alter_tenderdocument_ai_summary"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="tender",
            name="tender_status_idx",
        ),
        migrations.RemoveIndex(
            model_name="tender",
            name="tender_created_idx",
        ),
        migrations.AddIndex(
            model_name="tender",
            index=models.Index(fields=["status", "-created_at"], name="tender_status_created_idx"),
        ),
        migrations.AddIndex(
            model_name="tender",
            index=models.Index(fields=["-created_at"], name="tender_created_idx"),
        ),
    ]
