# Generated by Django 6.0.6 on 2026-07-10 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0006_aijob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltender',
            name='reference',
            field=models.CharField(db_index=True, editable=False, help_text='Auto-generated, e.g. London Summit Consultancy Limited-2026-001.', max_length=60),
        ),
        migrations.AlterField(
            model_name='tender',
            name='reference',
            field=models.CharField(editable=False, help_text='Auto-generated, e.g. London Summit Consultancy Limited-2026-001.', max_length=60, unique=True),
        ),
    ]
