# Generated by Django 6.0.6 on 2026-06-28 05:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
        ('services', '0002_service_service_featured_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproject',
            name='completion_status',
            field=models.CharField(choices=[('completed', 'Completed'), ('ongoing', 'Ongoing'), ('in_design', 'In Design / Pre-Construction')], default='completed', max_length=20, verbose_name='Project Status'),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='gross_internal_area',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Gross Internal Area (m²)'),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='programme_months',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Programme Duration (months)'),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='project_value',
            field=models.CharField(blank=True, help_text='e.g. £5M–£10M', max_length=60, verbose_name='Contract Value'),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 6, 28, 5, 28, 34, 610181, tzinfo=datetime.timezone.utc), editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='completion_status',
            field=models.CharField(choices=[('completed', 'Completed'), ('ongoing', 'Ongoing'), ('in_design', 'In Design / Pre-Construction')], default='completed', max_length=20, verbose_name='Project Status'),
        ),
        migrations.AddField(
            model_name='project',
            name='gross_internal_area',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Gross Internal Area (m²)'),
        ),
        migrations.AddField(
            model_name='project',
            name='programme_months',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Programme Duration (months)'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_value',
            field=models.CharField(blank=True, help_text='e.g. £5M–£10M', max_length=60, verbose_name='Contract Value'),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='year',
            field=models.PositiveSmallIntegerField(verbose_name='Completion / Start Year'),
        ),
        migrations.AlterField(
            model_name='project',
            name='year',
            field=models.PositiveSmallIntegerField(verbose_name='Completion / Start Year'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_published', '-year', 'display_order'], name='portfolio_project_list_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_published', 'is_featured'], name='portfolio_project_featured_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_published', 'sector'], name='portfolio_project_sector_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['-updated_at'], name='portfolio_project_updated_idx'),
        ),
    ]
