# Generated by Django 6.0.6 on 2026-07-13 11:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_historicalproject_completion_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproject',
            name='blueprint_sheet',
            field=models.TextField(blank=True, help_text='High-fidelity 2D sheet — vector .pdf or .dwfx.', max_length=200, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'dwfx'])], verbose_name='Blueprint Sheet'),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='blueprint_sheet_size',
            field=models.PositiveBigIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='cad_file',
            field=models.TextField(blank=True, help_text='Raw engineering / infrastructure layout for download — .dwg, .dxf or .nwd.', max_length=200, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['dwg', 'dxf', 'nwd'])], verbose_name='CAD Download'),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='cad_file_size',
            field=models.PositiveBigIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='model_3d',
            field=models.TextField(blank=True, help_text="Interactive browser model. .glb / .gltf render live in the viewer; .ifc is offered as a download (not browser-renderable). Export uncompressed (no Draco/Meshopt) so it renders under the site's strict CSP.", max_length=200, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['glb', 'gltf', 'ifc'])], verbose_name='3D Interactive Model'),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='model_3d_size',
            field=models.PositiveBigIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='blueprint_sheet',
            field=models.FileField(blank=True, help_text='High-fidelity 2D sheet — vector .pdf or .dwfx.', max_length=200, upload_to='portfolio/blueprints/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'dwfx'])], verbose_name='Blueprint Sheet'),
        ),
        migrations.AddField(
            model_name='project',
            name='blueprint_sheet_size',
            field=models.PositiveBigIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='cad_file',
            field=models.FileField(blank=True, help_text='Raw engineering / infrastructure layout for download — .dwg, .dxf or .nwd.', max_length=200, upload_to='portfolio/cad/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['dwg', 'dxf', 'nwd'])], verbose_name='CAD Download'),
        ),
        migrations.AddField(
            model_name='project',
            name='cad_file_size',
            field=models.PositiveBigIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='model_3d',
            field=models.FileField(blank=True, help_text="Interactive browser model. .glb / .gltf render live in the viewer; .ifc is offered as a download (not browser-renderable). Export uncompressed (no Draco/Meshopt) so it renders under the site's strict CSP.", max_length=200, upload_to='portfolio/models_3d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['glb', 'gltf', 'ifc'])], verbose_name='3D Interactive Model'),
        ),
        migrations.AddField(
            model_name='project',
            name='model_3d_size',
            field=models.PositiveBigIntegerField(blank=True, editable=False, null=True),
        ),
    ]
